#!/usr/bin/env node
/* ============================================
   build-skill.mjs — generate the design-book skill's reference docs FROM the
   live engine, so the installable skill can never drift from the real compose
   surface. Run after changing genres/presets; `--check` fails if docs are stale.
   ============================================
     node skills/design-book/build-skill.mjs           # regenerate docs/*.md
     node skills/design-book/build-skill.mjs --check    # exit 1 if out of date
   ============================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { resolveVaultRoot } from '../../lib/vault.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS = join(__dirname, 'docs');
const require = createRequire(import.meta.url);
const root = resolveVaultRoot();
const fm = await import(pathToFileURL(join(root, 'mcp-server', 'server.js')).href);
const presets = require(join(root, 'taste', 'presets.js'));
const palettes = fm.parsePalettes(readFileSync(join(root, 'colors', 'palettes.css'), 'utf8'));

const HEAD = '<!-- GENERATED by build-skill.mjs from the live engine — do not edit by hand. -->\n\n';

function genresDoc() {
  const web = Object.entries(fm.GENRE_SEQUENCES).map(([g, seq]) =>
    `- **${g}** — ${seq.map((s) => s.slot).join(' → ')}`).join('\n');
  const mobile = Object.entries(fm.MOBILE_FLOWS || {}).map(([g, flow]) =>
    `- **${g}** — ${flow.map((s) => s.screen).join(' → ')}`).join('\n');
  const deck = Object.entries(fm.DECK_FLOWS || {}).map(([g, slides]) =>
    `- **${g}** — ${slides.map((s) => s.slide).join(' · ')}`).join('\n');
  return HEAD + `# Genres — section sequences (the skeleton per genre)

Pick a genre, compose its sequence, then fill each slot with a real vault snippet.
Aesthetic defaults: ${Object.entries(fm.GENRE_AESTHETIC).map(([g, a]) => `${g}→${a}`).join(', ')}.

## Web pages (platform: web)
${web}

## Mobile app flows (platform: mobile)
${mobile}

## Slide decks (platform: deck)
${deck}
`;
}

function tasteDoc() {
  const ps = (presets.presets || [])
    .map((p) => `- **${p.name}** — ${p.aesthetic} · ${p.palette} · ${p.fontPair} · ${p.motion} · ${p.density}`).join('\n');
  const byGroup = {};
  for (const p of palettes) (byGroup[p.group] = byGroup[p.group] || []).push(`${p.name} (${p.mode})`);
  const pal = Object.entries(byGroup).map(([g, list]) => `- **${g}** — ${list.join(', ')}`).join('\n');
  return HEAD + `# Taste — aesthetics, presets, palettes

One coordinated aesthetic per page. Apply on <body>: \`class="struct pal-<palette>" data-aesthetic data-font-pair data-motion data-density\`.

## Aesthetics
${(presets.AESTHETICS || ['minimal', 'editorial', 'energetic', 'luxury', 'playful', 'technical']).join(' · ')}

## Presets (resolve all axes at once)
${ps || '(see taste/presets.js)'}

## Palettes (${palettes.length})
${pal}
`;
}

const FILES = { 'genres.md': genresDoc(), 'taste.md': tasteDoc() };

if (process.argv.includes('--check')) {
  let stale = [];
  for (const [name, content] of Object.entries(FILES)) {
    let cur = ''; try { cur = readFileSync(join(DOCS, name), 'utf8'); } catch {}
    if (cur !== content) stale.push(name);
  }
  if (stale.length) { console.error('design-book skill docs are STALE: ' + stale.join(', ') + ' — run `node skills/design-book/build-skill.mjs`'); process.exit(1); }
  console.log('design-book skill docs in sync ✓');
} else {
  for (const [name, content] of Object.entries(FILES)) writeFileSync(join(DOCS, name), content);
  console.log('wrote ' + Object.keys(FILES).map((f) => 'docs/' + f).join(', '));
}
