#!/bin/bash
# ============================================================================
# make-app.sh — (re)build "Design Book.app": a double-click macOS launcher for
# the SDK-engine Design Book workbench. No terminal, no Electron, zero build
# load — just a .app bundle wrapping a shell launcher.
#
# It bakes THIS machine's absolute `node` + repo paths into the bundle, so the
# .app is portable to /Applications, the Desktop, anywhere. Re-run after moving
# the repo or switching node versions.
#
#   bash app/make-app.sh                 # builds ./Design Book.app
#   bash app/make-app.sh ~/Desktop       # also drops a copy on the Desktop
# ============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
# Prefer a STABLE node path — `command -v node` under fnm/nvm yields an ephemeral
# per-shell multishell path that won't exist on the next double-click.
NODE_BIN=""
for c in \
  "$HOME/.local/share/fnm/aliases/default/bin/node" \
  "$HOME/Library/Application Support/fnm/aliases/default/bin/node" \
  "$HOME/.nvm/alias/default" \
  /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
  [ -x "$c" ] && NODE_BIN="$c" && break
done
[ -z "$NODE_BIN" ] && NODE_BIN="$(command -v node || echo /usr/local/bin/node)"
PORT=4747
OUT="$REPO/Design Book.app"
EXTRA_DEST="${1:-}"

rm -rf "$OUT"
mkdir -p "$OUT/Contents/MacOS"

cat > "$OUT/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Design Book</string>
  <key>CFBundleDisplayName</key><string>Design Book</string>
  <key>CFBundleIdentifier</key><string>haus.dath.designbook</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>designbook</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>LSUIElement</key><false/>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST

cat > "$OUT/Contents/MacOS/designbook" <<'LAUNCHER'
#!/bin/bash
# Design Book — double-click launcher. GENERATED by app/make-app.sh; edit the
# generator, not this file. Reads the SDK key from the macOS Keychain (prompts
# once, never writes plaintext to disk), guarantees a keyed server on the port,
# then opens a chromeless app window.
NODE="__NODE__"
REPO="__REPO__"
PORT=__PORT__
SERVICE="designbook-anthropic"
URL="http://localhost:$PORT/"

# Runtime fallback if the baked node path ever moves (fnm/nvm version bump).
if [ ! -x "$NODE" ]; then
  for c in \
    "$HOME/.local/share/fnm/aliases/default/bin/node" \
    "$HOME/Library/Application Support/fnm/aliases/default/bin/node" \
    /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    [ -x "$c" ] && NODE="$c" && break
  done
fi

# --- SDK auth: Keychain first; first-run prompt otherwise. PREFER the subscription
#     OAuth token (claude setup-token → runs on the Max plan's Agent-SDK credit,
#     NOT metered) over a metered API key. --------------------------------------
OAUTH="$(security find-generic-password -s "$SERVICE" -a oauth -w 2>/dev/null || true)"
KEY="$(security find-generic-password -s "$SERVICE" -a key -w 2>/dev/null || true)"
if [ -z "$OAUTH" ] && [ -z "$KEY" ]; then
  OAUTH="$(osascript -e 'text returned of (display dialog "Paste your Claude subscription token (Terminal: claude setup-token). Runs on your Max plan, not metered." default answer "" with hidden answer buttons {"Cancel","Save"} default button "Save")' 2>/dev/null || true)"
  [ -z "$OAUTH" ] && exit 0
  security add-generic-password -s "$SERVICE" -a oauth -w "$OAUTH" -U 2>/dev/null || true
fi
if [ -n "$OAUTH" ]; then
  unset ANTHROPIC_API_KEY                          # force subscription billing, not metered
  export CLAUDE_CODE_OAUTH_TOKEN="$OAUTH"
else
  export ANTHROPIC_API_KEY="$KEY"
  BASE="$(security find-generic-password -s "$SERVICE" -a baseurl -w 2>/dev/null || true)"
  [ -n "$BASE" ] && export ANTHROPIC_BASE_URL="$BASE"
fi

# --- ensure a server WITH the key is live on the port --------------------------
health="$(curl -s "http://localhost:$PORT/api/health" 2>/dev/null || true)"
if [ -n "$health" ]; then
  case "$health" in
    *'"hasKey":true'*) : ;;                                          # keyed — reuse
    *) lsof -ti tcp:$PORT 2>/dev/null | xargs kill 2>/dev/null || true; sleep 0.6; health="" ;;
  esac
fi
if [ -z "$health" ]; then
  cd "$REPO"
  nohup "$NODE" server.js > "$REPO/.app-server.log" 2>&1 &
  for i in $(seq 1 60); do curl -s "http://localhost:$PORT/api/health" >/dev/null 2>&1 && break; sleep 0.2; done
fi

# --- open a chromeless app window (fallback: default browser) -------------------
PROFILE="$HOME/Library/Application Support/DesignBookApp"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
EDGE="/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge"
BRAVE="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"
if   [ -x "$CHROME" ]; then "$CHROME" --app="$URL" --user-data-dir="$PROFILE" >/dev/null 2>&1 &
elif [ -x "$EDGE" ];   then "$EDGE"   --app="$URL" --user-data-dir="$PROFILE" >/dev/null 2>&1 &
elif [ -x "$BRAVE" ];  then "$BRAVE"  --app="$URL" --user-data-dir="$PROFILE" >/dev/null 2>&1 &
else open "$URL"; fi
LAUNCHER

# bake the machine-specific paths into the launcher
sed -i '' "s|__NODE__|$NODE_BIN|g; s|__REPO__|$REPO|g; s|__PORT__|$PORT|g" "$OUT/Contents/MacOS/designbook"
chmod +x "$OUT/Contents/MacOS/designbook"
echo "built: $OUT"
echo "  node=$NODE_BIN"
echo "  repo=$REPO"

if [ -n "$EXTRA_DEST" ]; then
  DEST_DIR="${EXTRA_DEST/#\~/$HOME}"
  rm -rf "$DEST_DIR/Design Book.app"
  cp -R "$OUT" "$DEST_DIR/"
  echo "  copied → $DEST_DIR/Design Book.app"
fi
