/* ============================================
   designbook · lib/handoff.js — mobile developer handoff
   ============================================
   When a MOBILE design is exported, the ZIP carries a FLOW.md alongside the
   rendered index.html: the screen flow, the resolved design tokens, and the
   device geometry an engineer needs to rebuild the app natively (SwiftUI /
   Jetpack Compose / React Native). Web exports don't get this — it's the
   mobile peer of "here's the page", expressed as a spec instead of a screenshot.
   ============================================ */

// The composed app-flow signature — same test the UI and inspect lab use.
export function isMobileHtml(html) {
  return /class="[^"]*\bapp-flow\b|\bscr-frame\b/.test(String(html || ''));
}

// Pull the taste axes the page was composed with off its <body> tag.
function readBodyAxes(html) {
  const body = (String(html).match(/<body[^>]*>/i) || [''])[0];
  const pick = (re) => (body.match(re) || [null, ''])[1];
  return {
    palette: (pick(/class="[^"]*\bpal-([a-z0-9-]+)/i) || '').trim(),
    aesthetic: pick(/data-aesthetic="([^"]*)"/i),
    fontPair: pick(/data-font-pair="([^"]*)"/i),
    motion: pick(/data-motion="([^"]*)"/i),
    density: pick(/data-density="([^"]*)"/i),
  };
}

// Each frame is preceded by `<!-- Name (shell): drop in COMPONENT -->`.
function readScreens(html, manifest) {
  const out = [];
  const re = /<!--\s*([^(<]+?)\s*\(([a-z]+)\)\s*:\s*(?:drop in\s+)?(.*?)\s*-->/gi;
  let m;
  while ((m = re.exec(html))) {
    const comp = (m[3] || '').trim();
    out.push({ name: m[1].trim(), shell: m[2].trim(), component: /^\(/.test(comp) ? null : (comp || null) });
  }
  if (out.length) return out;
  // fallback: manifest.screens may just be a list of shells
  return (manifest?.screens || []).map((s, i) => ({ name: `Screen ${i + 1}`, shell: String(s), component: null }));
}

// shell → navigation role, so the handoff shows the real screen graph
const ROOT_SHELLS = new Set(['feed', 'dashboard', 'profile', 'list', 'settings', 'fablist', 'empty']);
const MODAL_SHELLS = new Set(['onboarding', 'auth', 'paywall', 'checkout', 'player', 'sheet', 'splash']);
function screenRole(shell) { return ROOT_SHELLS.has(shell) ? 'tab root' : MODAL_SHELLS.has(shell) ? 'modal / focused' : 'pushed'; }

export function buildFlowHandoff({ html, manifest, palettes }) {
  const axes = readBodyAxes(html);
  const screens = readScreens(html, manifest);
  const pal = (palettes || []).find((p) => p.name === axes.palette);
  const tok = (pal && pal.tokens) || {};
  const title = manifest?.title || manifest?.slug || 'Mobile app';
  const genre = manifest?.genre ? ` · ${manifest.genre}` : '';

  const tokenLine = (label, key) => (tok[key] ? `  - ${label}: \`${tok[key]}\`\n` : '');
  const flowList = screens
    .map((s, i) => `${i + 1}. **${s.name}** — \`${s.shell}\` (${screenRole(s.shell)})${s.component ? ` → real component: \`${s.component}\`` : ''}`)
    .join('\n');
  const roots = screens.filter((s) => ROOT_SHELLS.has(s.shell)).map((s) => s.name);

  return `# ${title} — mobile handoff${genre}

Generated by **Design Book** from the *frontendmaxxing* vault. This is a native-app
UI spec, not a screenshot: the screen flow, the resolved design tokens, and the
device geometry. Rebuild it natively (SwiftUI · Jetpack Compose · React Native)
against these values, or open \`index.html\` in a browser to preview the flow.

## Screen flow (${screens.length})
${flowList || '_no screens detected_'}

Tab roots (reachable from the bottom bar): ${roots.length ? roots.map((r) => `**${r}**`).join(', ') : '—'}. The rest are pushed or modal.
Each screen is built from the \`.scr-*\` shells in \`structure/app-shell.css\`
(status bar, nav bar, scrolling body, tab bar, FAB, bottom sheet, bottom CTA). The
shells already reserve the safe areas — port the structure, not the pixels.

## Design tokens
- Palette: \`pal-${axes.palette || '—'}\`${pal ? ` (${pal.mode || 'mode'} · ${pal.group || ''})` : ''}
${tokenLine('background', 'bg')}${tokenLine('surface', 'surface')}${tokenLine('foreground', 'fg')}${tokenLine('accent', 'accent')}${tokenLine('on-accent', 'on-accent')}
- Type pair: \`${axes.fontPair || '—'}\`  (set via \`data-font-pair\`)
- Motion: \`${axes.motion || '—'}\`  ·  Density: \`${axes.density || '—'}\`  ·  Aesthetic: \`${axes.aesthetic || '—'}\`

## Device geometry (iPhone 14/15 reference — Android varies, read insets at runtime)
- Screen: **390 × 844 pt** (\`--scr-w\` / \`--scr-h\`)
- Safe area: **47 pt** top (Dynamic Island) · **34 pt** bottom (home indicator). Android: read \`WindowInsets\` (status bar + gesture nav) — do not hardcode.
- Radius: 14 pt cards · 26 pt pill buttons · Gutter: 16 pt

## iOS ↔ Android — build both, don't ship an iPhone clone on Android
| Concern | iOS (HIG) | Android (Material 3) |
|---|---|---|
| Primary nav | Tab bar, bottom | Navigation bar, bottom (rail on tablet) |
| Back | ‹ chevron top-left + edge-swipe | ← up arrow + system back gesture |
| Min tap target | 44 × 44 pt | 48 × 48 dp |
| Type | SF Pro / SF Compact | Roboto or your brand face |
| Title | Large title, collapses on scroll | Top app bar (small / medium / large) |
| Primary create action | Bottom CTA or context bar | **FAB** |
| Item detail from a list | Sheet w/ grabber, swipe to dismiss | Bottom sheet (modal / standard) |
| Corner radius | ~12–16 pt | 16–28 dp (Material expressive) |
| Elevation | Soft shadow / material blur | Tonal elevation + shadow |

These shells are tuned to the iOS reference; map each row to the Android column when targeting Compose.

## Conventions baked into the flow
- Tab roots carry a **tab bar**; pushed screens carry a **back** affordance; modals (sheet/player) dismiss by swipe.
- Bottom bars (\`.scr-tabbar\` / \`.scr-cta\`) **reserve the home-indicator strip** (safe-area padding).
- Primary actions sit in the lower **thumb-reach** zone.

## Files
- \`index.html\` — the rendered screen flow (preview in any browser)
- \`assets/\` — vault CSS (\`app-shell.css\`, palettes, taste layers) + any project images

_Verify against the Design Book mobile lab (\`book_inspect mode:"mobile"\`): per-screen
safe-area, thumb-reach, tap-target and nav-convention facts._
`;
}
