/* ============================================
   designbook · lib/handoff.js — mobile developer handoff
   ============================================
   When a MOBILE design is exported, the ZIP carries a FLOW.md alongside the
   rendered index.html: the screen flow, the resolved design tokens, and the
   device geometry an engineer needs to rebuild the app natively (SwiftUI /
   Jetpack Compose / React Native). Web exports don't get this — it's the
   mobile peer of "here's the page", expressed as a spec instead of a screenshot.
   ============================================ */

// The composed app-flow signature — same test the UI and inspect lab use.
export function isMobileHtml(html) {
  return /class="[^"]*\bapp-flow\b|\bscr-frame\b/.test(String(html || ''));
}

// Pull the taste axes the page was composed with off its <body> tag.
function readBodyAxes(html) {
  const body = (String(html).match(/<body[^>]*>/i) || [''])[0];
  const pick = (re) => (body.match(re) || [null, ''])[1];
  return {
    palette: (pick(/class="[^"]*\bpal-([a-z0-9-]+)/i) || '').trim(),
    aesthetic: pick(/data-aesthetic="([^"]*)"/i),
    fontPair: pick(/data-font-pair="([^"]*)"/i),
    motion: pick(/data-motion="([^"]*)"/i),
    density: pick(/data-density="([^"]*)"/i),
  };
}

// Each frame is preceded by `<!-- Name (shell): drop in … -->` (renderComposedApp).
function readScreens(html, manifest) {
  const out = [];
  const re = /<!--\s*([^(<]+?)\s*\(([a-z]+)\)\s*:/gi;
  let m;
  while ((m = re.exec(html))) out.push({ name: m[1].trim(), shell: m[2].trim() });
  if (out.length) return out;
  // fallback: manifest.screens may just be a list of shells
  return (manifest?.screens || []).map((s, i) => ({ name: `Screen ${i + 1}`, shell: String(s) }));
}

export function buildFlowHandoff({ html, manifest, palettes }) {
  const axes = readBodyAxes(html);
  const screens = readScreens(html, manifest);
  const pal = (palettes || []).find((p) => p.name === axes.palette);
  const tok = (pal && pal.tokens) || {};
  const title = manifest?.title || manifest?.slug || 'Mobile app';
  const genre = manifest?.genre ? ` · ${manifest.genre}` : '';

  const tokenLine = (label, key) => (tok[key] ? `  - ${label}: \`${tok[key]}\`\n` : '');
  const flowList = screens
    .map((s, i) => `${i + 1}. **${s.name}** — \`${s.shell}\` screen shell`)
    .join('\n');

  return `# ${title} — mobile handoff${genre}

Generated by **Design Book** from the *frontendmaxxing* vault. This is a native-app
UI spec, not a screenshot: the screen flow, the resolved design tokens, and the
device geometry. Rebuild it natively (SwiftUI · Jetpack Compose · React Native)
against these values, or open \`index.html\` in a browser to preview the flow.

## Screen flow (${screens.length})
${flowList || '_no screens detected_'}

Each screen is built from the \`.scr-*\` shells in \`structure/app-shell.css\`
(status bar, nav bar, scrolling body, tab bar, FAB, bottom CTA). The shells already
reserve the safe areas — port the structure, not the pixels.

## Design tokens
- Palette: \`pal-${axes.palette || '—'}\`${pal ? ` (${pal.mode || 'mode'} · ${pal.group || ''})` : ''}
${tokenLine('background', 'bg')}${tokenLine('surface', 'surface')}${tokenLine('foreground', 'fg')}${tokenLine('accent', 'accent')}${tokenLine('on-accent', 'on-accent')}
- Type pair: \`${axes.fontPair || '—'}\`  (set via \`data-font-pair\`)
- Motion: \`${axes.motion || '—'}\`  ·  Density: \`${axes.density || '—'}\`  ·  Aesthetic: \`${axes.aesthetic || '—'}\`

## Device geometry (iPhone reference)
- Screen: **390 × 844 pt** (\`--scr-w\` / \`--scr-h\`)
- Safe area: **47 pt** top (Dynamic Island) · **34 pt** bottom (home indicator)
- Tap target: **≥ 44 pt** (Apple HIG) / 48 dp (Material) — comfortable 48 pt
- Radius: 14 pt cards · 26 pt pill buttons · Gutter: 16 pt

## Conventions baked into the flow
- Top-level screens carry a **tab bar**; pushed/detail screens carry a **back** affordance.
- Bottom tab bars and CTA bars **reserve the home-indicator strip** (safe-area padding).
- Primary actions sit in the lower **thumb-reach** zone.

## Files
- \`index.html\` — the rendered screen flow (preview in any browser)
- \`assets/\` — vault CSS (\`app-shell.css\`, palettes, taste layers) + any project images

_Verify against the Design Book mobile lab (\`book_inspect mode:"mobile"\`): per-screen
safe-area, thumb-reach, tap-target and nav-convention facts._
`;
}
